### ISSUE TITLE
Multi-account login

### ISSUE THREAD

**Issue by container1** [Firefly-Social/Firefly#100]
Multi-account login not yet given?!
...is it a planned feature for later?
And sorry, but are there no App settings?
PS: same for Mozilla Social
Thx

**Comment by container1** [comment]
For clarification:
Seems implementation only given for multi account for single Instance but not single account for multi Instances?!
From my perspective, "Multi-Account login" suggest ability using Multiple Accounts, Instance independent.
Already given in Fedilab-, Kaiteki-, Mastodon-, Megalodon-, Moschidon-, Tusky-, Subway Tooter-App!?!

**Comment by JohnOberhauser** [comment]
Completed in moso and ported here
