### ISSUE TITLE
Update "posts and replies" profile tab to be "replies"

### ISSUE THREAD

**Issue by devotaaabel** [Firefly-Social/Firefly#49]

**Comment by JohnOberhauser** [comment]
I think it's nice to have a column with posts and replies as a way to see all the users activity in one feed.  Especially if they are replying to a post they created.

I'm thinking it could be nice to have these columns:

Posts - contains post and replies.  Does not contain boosts
Boosts - only boosts
Media - Posts with media, does not contain boosts


Or we could do 4 columns

Posts
Posts + replies
Boosts
Media

**Comment by cadeyrn** [comment]
It would also be nice to have a column for replies only. To quote myself from https://github.com/MozillaSocial/mozilla-social-android/issues/450:

> There are currently three tabs on the profile pages: "Posts", "Posts and Replies", and "Media". That's okay because it's exactly the same as what the official Mastodon app does.
> 
> But sometimes I'm just interested in seeing if an account is replying to other users, or I'm looking for a comment of my own that I know was a reply.
> 
> So I suggest adding a "Replies" tab. The advantage would also be that this would be a way to stand out from the official Mastodon app with another special feature (after the discover feature).
> 
> Threads, by the way, has exactly this feature. Even though I don't usually like Threads very much, maybe this at least confirms that I'm not the only one who sees a use case in this feature. 😄

**Comment by JohnOberhauser** [comment]
So maybe 5 columns would be useful

All
Posts
Replies
Boosts
Media

Although 5 tabs seems like a lot.  Maybe we should have 1 feed and use filters with chips

https://m3.material.io/components/chips/overview

**Comment by cederbs** [comment]
@JohnOberhauser 5 is a lot, I'd definitely agree. I think if the approach is going to be to let people filter the types of content, one feed with filter chips along the top of that feed would be a really good place. Are you thinking it would be multi-select? Or is it single selection? 
(linking to this part since it outlines some of the behavioral differences) https://m3.material.io/components/chips/guidelines#11bc122b-5203-4cf5-bb12-470d86ecd3b5

**Comment by JohnOberhauser** [comment]
Closing this ticket due to the limitations of the mastodon api.  These are the options when fetching posts:
- only_media
- exclude_replies
- exclude_reblogs
- pinned
- tagged (specific hash tags)
